import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import Layout from '@/components/layout/layout';
import { QueryProvider } from '@/providers/query-provider';
import SessionProvider from '@/providers/session-provider';
import ThemeProvider from '@/providers/theme-provider';
import './globals.css';

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko' className='scroll-smooth' suppressHydrationWarning>
      <body className='antialiased'>
        <QueryProvider>
          <SessionProvider>
            <ThemeProvider>
              <Layout>{children}</Layout>
              <Toaster position='top-center' richColors />
            </ThemeProvider>
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
